before_script:
  - "psql -c 'create database ct2_test;' -U postgres"
  - "sh -e /etc/init.d/xvfb start"
script: "DISPLAY=:99.0 bundle exec rake"
notifications:
  email:
    - sven.steinheisser@gmail.com
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
